name: build-deploy-gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Build Jekyll
        run: bundle exec jekyll build
      - uses: actions/upload-pages-artifact@v3
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
